[project]
name = "2-agentic-ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.104.1",
    "faiss-cpu>=1.14.2",
    "fastmcp>=2.0.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "kagglehub>=1.0.1",
    "langchain>=1.3.1",
    "langchain-anthropic>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.2.2",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.1",
    "mlflow>=3.12.0",
    "numpy>=2.4.6",
    "openai>=2.38.0",
    "pandas>=2.3.3",
    "pydantic>=2.13.4",
    "pypdf>=6.12.1",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.5.1",
    "tavily-python>=0.7.24",
    "voyageai>=0.3.7",
]
